# Generated by Django 5.2.8 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_monthly_baseline_hours_employee_pod_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HOD', 'Head of Department'), ('POD_LEAD', 'Pod Lead'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('AUTOMATION', 'Automation')], default='EMPLOYEE', max_length=20),
        ),
    ]
