# Generated by Django 5.2.8 on 2025-11-13 09:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('parse_summary', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='core.employee')),
            ],
            options={
                'db_table': 'raw_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_month', models.DateField()),
                ('effort_hours', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.employee')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='core.feature')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.pod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.product')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_records', to='contributions.rawfile')),
            ],
            options={
                'db_table': 'contribution_records',
                'ordering': ['-contribution_month', 'employee'],
                'indexes': [models.Index(fields=['contribution_month'], name='idx_contrib_month'), models.Index(fields=['product', 'contribution_month'], name='idx_contrib_prod_month'), models.Index(fields=['pod', 'contribution_month'], name='idx_contrib_pod_month'), models.Index(fields=['department', 'contribution_month'], name='idx_contrib_dept_month'), models.Index(fields=['employee', 'contribution_month'], name='idx_contrib_emp_month')],
            },
        ),
    ]
