# Generated by Django 5.2.8 on 2025-11-13 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('core', '0002_employee_monthly_baseline_hours_employee_pod_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodLeadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_month', models.DateField()),
                ('academy_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('intensive_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('niat_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('features_text', models.TextField(blank=True, null=True)),
                ('features_verified', models.BooleanField(default=False)),
                ('baseline_hours', models.DecimalField(decimal_places=2, default=Decimal('160.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.employee')),
                ('pod_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_employees', to='core.employee')),
            ],
            options={
                'db_table': 'pod_lead_allocations',
                'ordering': ['-contribution_month', 'employee'],
                'indexes': [models.Index(fields=['pod_lead', 'contribution_month'], name='idx_alloc_pod_lead_month'), models.Index(fields=['employee', 'contribution_month'], name='idx_alloc_emp_month'), models.Index(fields=['status', 'contribution_month'], name='idx_alloc_status_month')],
                'unique_together': {('employee', 'contribution_month')},
            },
        ),
    ]
