# Generated by Django 5.2.8 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_podleadallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='podleadallocation',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podleadallocation',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='podleadallocation',
            old_name='features_verified',
            new_name='is_verified_description',
        ),
        migrations.AlterUniqueTogether(
            name='podleadallocation',
            unique_together={('employee', 'contribution_month', 'product')},
        ),
    ]
